### PR TITLE
Allow to choose luatest cases to run

### LINKED ISSUE #339: Allow to choose luatest cases to run
From luatest help:

```
  -p, --pattern PATTERN:  Execute all test names matching the Lua PATTERN
                          May be repeated to include several patterns
                          Make sure you escape magic chars like +? with %
```

It'd be nice if test-run had a similar option, because a developer is usually only interested in a subset of tests in a test file - the ones that are currently being written/tested. (Currently, test-run always runs all test cases in a file, which may take long.)

### PR DESCRIPTION
**Pull request by ylobankov**
Closes #339

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
Looks good on a glance!

Please, close #339 from this commit/PR.

**Comment by Totktonada** [comment]
Ah, no, just one problem :)

> python -m flake8 *.py lib/*.py
> lib/options.py:328:76: W291 trailing whitespace

**Comment by ylobankov** [comment]
> Ah, no, just one problem :)
> 
> > python -m flake8 _.py lib/_.py
> > lib/options.py:328:76: W291 trailing whitespace

Fixed.

**Comment by Totktonada** [comment]
I found a problem. Please, try the following test on test-run's master:

```
./test/test-run.py --force engine-luatest/gh_6436_field_constraint_test.lua
```

Tracked down to the unexpected shuffle value:

```diff
diff --git a/luatest/runner.lua b/luatest/runner.lua
index e141869..0b33423 100644
--- a/luatest/runner.lua
+++ b/luatest/runner.lua
@@ -461,6 +461,8 @@ function Runner.mt:find_tests()
 
     local result = {}
 
+    print('SSSSH: ' .. tostring(self.shuffle))
+
     for _, name in ipairs(self.test_names or self:all_test_names()) do
         local group = self.groups[name]
         if group then
```

```
[001] SSSSH: group
```

After returning back `<...>, '--shuffle', 'none']` into the Popen call it is `none`:

```
[001] SSSSH: none
```

I don't investigate it further.

**Comment by Totktonada** [comment]
Filed https://github.com/tarantool/luatest/issues/306. It was fixed in https://github.com/tarantool/luatest/pull/307 against luatest itself. The change will go to test-run in https://github.com/tarantool/test-run/pull/390.

**Pull request merged**
