### PR TITLE
Update tarantool-python to 0.7.1-1-g8847b8c

### PR DESCRIPTION
**Pull request by Totktonada**
This update brings tarantool-python changes from releases 0.6.6[^1],
0.7.0 and 0.7.1 and the unreleased change [1] regarding unification of
the \_\_str\_\_ Response method across Python 2 and Python 3. Look at the
release notes [2] for the list of changes in the connector.

We need [1] to obtain the same test result on different Python versions
for tarantool's box-py/call.test.py test.

[^1]: Except replacing of yaml.load() with yaml.safe_load() in tests,
      which is already here.

[1]: https://github.com/tarantool/tarantool-python/pull/186
[2]: https://github.com/tarantool/tarantool-python/releases

Part of #20
Part of https://github.com/tarantool/tarantool/issues/5652

### CODE REVIEW

**Comment by ligurio** [comment]
I propose to include changes in PR https://github.com/tarantool/tarantool-python/pull/187 too, because it is required to completely fix `box-py/call.test.py` test.

**Review by ligurio — APPROVED** [review]
LGTM

**Comment by Totktonada** [comment]
Thanks, I'll proceed soon.

**Comment by Totktonada** [comment]
Updated the test-run submodule in tarantool in [2.8.0-21-gfc86213cd](https://github.com/tarantool/tarantool/commit/fc86213cd7cda0641df95b1a81949bab85c19fce), 2.7.1-20-g8c07ab317, 2.6.2-19-gb95bb7e8f, 1.10.9-7-gc252616dd.

`test/box-py/iproto.test.py` requires a tiny update, see the linked commit.

**Pull request merged**
