### PR TITLE
Retry on a Lua error in test_run:wait_cond()

### PR DESCRIPTION
**Pull request by Totktonada**
Also re-raise an error in test_run:eval() for better error reporting.

See the linked issue and commit messages for details.

Fixes https://github.com/tarantool/tarantool-qa/issues/128.

### CODE REVIEW

**Comment by Totktonada** [comment]
I'll wait for at least one 'ok' from development and at least one 'ok' from QA.

**Review by sergepetrenko — APPROVED** [review]
Thanks! LGTM.

**Review by avtikhon — APPROVED** [review]
Right, the change is really needed, thanks for the patchset it LGTM.

**Review by Gerold103 — APPROVED** [review]

**Review by kyukhin — APPROVED** [review]

**Comment by Totktonada** [comment]
The test-run submodule is updated in tarantool in [2.9.0-109-gdde0fedd3](https://github.com/tarantool/tarantool/commit/dde0fedd37d3c3a1db5c11e45754aff4269fe6a9), 2.8.1-79-gaa60a49b1, 2.7.2-65-g183f859b6, 1.10.10-29-g3d757cc72.

**Pull request merged**
